
sw_version = "v1.0_20251205"
config_file_path = "./"     # file path for log yaml configure file and pcs csv file

#goose interfaces for simulatior PC 
goose_interface_lan1 = "enp1s0f0" #lan 
goose_interface_lan2 = "enp1s0f1" #lan 
# Validity checking interval in milliseconds
validity_interval_ms = "5000"
