appenders:
  my_stdout:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)} - {l}: {m}{n})}"
  my_file_logger:
    kind: rolling_file
    path: "log/pcsgoose.log"
    encoder:
      pattern: "{d} - {h({l})}: {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 15000kb
      roller:
        kind: fixed_window
        base: 1
        count: 50
        pattern: "log/pcs_simulator{}.log"
root:
  level: debug
  appenders:
    - my_file_logger
